name: NPM Build
description: Builds an npm project
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  NODE_VERSION:
    description: The node version to use.
    required: false
    default: "16"

  BUILD_DIR:
    description: The directory to change
    required: false
    default: ""


runs:
  using: composite
  steps:
    - name: Checkout Branch
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTP authentication
      shell: bash
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.NODE_VERSION }}
  
    - shell: bash
      working-directory: ${{ inputs.BUILD_DIR }}
      run: npm ci

    - shell: bash
      working-directory: ${{ inputs.BUILD_DIR }}
      run: npm run build

branding:
  icon: package
  color: blue
