name: Yarn Build
description: Builds a yarn project
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  NODE_VERSION:
    description: The node version to use.
    required: false
    default: "16"

  INSTALL_COMMAND:
    description: The install command to use.
    required: false
    default: yarn

  BUILD_COMMAND:
    description: The build command to use.
    required: false
    default: yarn


runs:
  using: composite
  steps:
    - name: Checkout Branch
      uses: actions/checkout@master
      with:
        persist-credentials: false

    - name: Reconfigure git to use HTTP authentication
      shell: bash
      run: >
        git config --global url."https://github.com/".insteadOf
        ssh://git@github.com/

    - uses: actions/setup-node@v1
      with:
        node-version: ${{ inputs.NODE_VERSION }}

    - shell: bash
      run: ${{ inputs.INSTALL_COMMAND }}

    - shell: bash
      run: ${{ inputs.BUILD_COMMAND }}


branding:
  icon: package
  color: blue
