name: Get JSON File
description: Reads JSON data into the action
author: Selig Labs, Inc <info@seliglabs.com>

inputs:
  PATH:
    description: Path to file
    required: false
    default: ./package.json
outputs:
  jsonData:
    description: JSON Data

runs:
  using: node16
  main: $GITHUB_ACTION_PATH/dist/index.js

branding:
  icon: box
  color: blue
